# Config file for CelebA dataset (200k)

output_dir: 'Y:/user/yrso/result/StyleGAN_celebAhq/try2/'
structure: 'linear'
conditional: False
n_classes: 0
device_id: ('0')
checkpoint_factor: 10
feedback_factor: 10
dataset:
  img_dir: 'Y:/user/yrso/data/celebA_hq/train'
  folder: True
  resolution: 512
  channels: 3
model:
  gen:
    mapping_layers: 8
    # Negative numbers represent no truncation layers
    truncation_psi: 0.7
    latent_size: 512
sched:
  epochs: [4, 4, 4, 4, 8, 16, 32, 64]
  batch_sizes: [16, 16, 16, 8, 4, 4, 2, 1, 1]
  fade_in_percentage: [50, 50, 50, 50, 50, 50, 50, 50, 50]